### ISSUE TITLE
URIError: Failed to decode param '/%PUBLIC_URL%/favicon.ico'

### ISSUE THREAD

**Issue by jsanguin** [bradtraversy/react-crash-2021#1]
Good evening Brad:
I have cloned this repository in my local machine (Ubuntu Linux), followed all the instructions in Read-me. I get this error :

Compiled successfully!

You can now view react-task-tracker in the browser.

  Local:            http://localhost:3000/bradtraversy/react-crash-202
  On Your Network:  http://192.168.86.46:3000/bradtraversy/react-crash-202

Note that the development build is not optimized.
To create a production build, use yarn build.

URIError: Failed to decode param '/%PUBLIC_URL%/favicon.ico'
    at decodeURIComponent (<anonymous>)
    at decode_param (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:574:18)
    at next (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:317:13)
    at /home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:335:12)
URIError: Failed to decode param '/%PUBLIC_URL%/manifest.json'
    at decodeURIComponent (<anonymous>)
    at decode_param (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:574:18)
    at next (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:317:13)
    at /home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:335:12)
URIError: Failed to decode param '/bradtraversy/react-crash-2021/%PUBLIC_URL%/favicon.ico'
    at decodeURIComponent (<anonymous>)
    at decode_param (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:574:18)
    at next (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:317:13)
    at /home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:335:12)
URIError: Failed to decode param '/bradtraversy/react-crash-2021/%PUBLIC_URL%/manifest.json'
    at decodeURIComponent (<anonymous>)
    at decode_param (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:574:18)
    at next (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:317:13)
    at /home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:335:12)
URIError: Failed to decode param '/%PUBLIC_URL%/manifest.json'
    at decodeURIComponent (<anonymous>)
    at decode_param (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:574:18)
    at next (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:317:13)
    at /home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:335:12)
URIError: Failed to decode param '/%PUBLIC_URL%/favicon.ico'
    at decodeURIComponent (<anonymous>)
    at decode_param (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:574:18)
    at next (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:317:13)
    at /home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:335:12)
URIError: Failed to decode param '/%PUBLIC_URL%/manifest.json'
    at decodeURIComponent (<anonymous>)
    at decode_param (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:574:18)
    at next (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:317:13)
    at /home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:335:12)
URIError: Failed to decode param '/%PUBLIC_URL%/favicon.ico'
    at decodeURIComponent (<anonymous>)
    at decode_param (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:574:18)
    at next (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:317:13)
    at /home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/jorge/Sites/react-crash-2021/node_modules/express/lib/router/index.js:335:12)

**Comment by alexbaker2002** [comment]
https://stackoverflow.com/questions/50824024/urierror-failed-to-decode-param-public-url-favicon-ico

hope this helps

**Comment by andyaspel** [comment]
I think you are linking wrong file paths.
URIError: Failed to decode param '**/bradtraversy/react-crash-2021**/%PUBLIC_URL%/favicon.ico'

**Comment by matheus4lves** [comment]
Thanks @andyaspel ! I was having some trouble with this error since I decided to replace the create-react-app with my own configuration, due some kind of bug that was making my browsers eat all my ram. I completely forgot to check the index.html and there was some links there causing the error.

**Comment by redpredator8** [comment]
Fix: if you have github, revert to the last change you did / unistall recent libraries

I updated my mac and this started happening, was killing my brain tbh. Im pretty sure it was bc i installed firebase tools and that messed up something because i updated my mac and maybe smth didnt save by mac time-machine so it was throwing a weird hidden syntax error that was preventing the app to be displayed. I tried fixing all the errors like the guys up top are saying fixing the links etc but brand new shit was popping up and I was like nahh. no way i have to recode Node to fix this shit.

Options: Revert to previous version / uninstall recent installed libraries / Create a new react app and just copy your src folder to the new app

leave a thubs up: )
